---
# - debug:
#     msg: "Hello Arch! Woe"

- name: Dependency
  community.general.pacman:
    name:
    - patch
    - yay
    - base-devel  # Fix
    state: latest
    # update_cache: true
  become: true
  when: false

# Broken:
- name: Install WoeUSB-ng
  kewlfft.aur.aur:
    name: woeusb-ng
    use: makepkg
    state: present
  become: yes
  become_user: aur_builder

# By hand works:
#`yay -S woeusb-ng`
# ||
#`pamac build woeusb-ng`
